"""Validate and sanitise SQL generated by the text-to-SQL agent.

Uses ``sqlglot`` to parse the SQL into an AST and inspect the statement type.
Only SELECT statements are allowed.  Any DDL, DML, DCL, TCL, or otherwise
destructive / state-changing SQL is rejected before it reaches the database.
"""

from __future__ import annotations
import logging
import sqlglot
from sqlglot import exp

logger = logging.getLogger(__name__)

# AST node types that represent read-only queries
_ALLOWED_NODES: frozenset[type[exp.Expression]] = frozenset({exp.Select})

# AST node types that must never appear anywhere in the tree
_FORBIDDEN_NODES: tuple[type[exp.Expression], ...] = (
    exp.Insert,
    exp.Update,
    exp.Delete,
    exp.Drop,
    exp.Create,
    exp.Alter,
    exp.AlterColumn,
    exp.Command,
    exp.Transaction,
    exp.Commit,
    exp.Rollback,
    exp.Grant,
    exp.Set,
)

# Table names that must never be accessed
_FORBIDDEN_TABLES: frozenset[str] = frozenset({
    "pg_catalog",
    "pg_stat_activity",
    "pg_roles",
    "pg_shadow",
    "pg_authid",
    "information_schema",
})

class SQLValidationError(Exception):
    """Raised when the generated SQL fails safety checks."""

def validate_sql(sql: str) -> str:
    """Return the cleaned SQL string, or raise ``SQLValidationError``.

    Steps
    -----
    1. Strip leading/trailing whitespace and trailing semicolons.
    2. Parse with ``sqlglot`` using the ``postgres`` dialect.
    3. Must yield exactly one statement whose root is a SELECT.
    4. Walk the entire AST — reject if any forbidden node type is found.
    5. Inspect referenced table names — reject system catalogs.
    """
    cleaned = sql.strip().rstrip(";").strip()
    if not cleaned:
        raise SQLValidationError("Empty SQL statement.")

    try:
        statements = sqlglot.parse(cleaned, dialect="postgres")
    except sqlglot.errors.ParseError as exc:
        raise SQLValidationError(f"SQL could not be parsed: {exc}") from exc

    statements = [s for s in statements if s is not None]

    if len(statements) != 1:
        raise SQLValidationError(
            f"Expected exactly one SQL statement, got {len(statements)}. "
            "Multiple statements are not allowed."
        )

    tree = statements[0]

    if type(tree) not in _ALLOWED_NODES:
        raise SQLValidationError(
            f"Only SELECT statements are allowed. "
            f"Got: {type(tree).__name__}."
        )

    # Reject SELECT … INTO (creates a new table from a SELECT)
    if tree.find(exp.Into):
        raise SQLValidationError(
            "SELECT INTO is not allowed (it creates a new table)."
        )

    for node in tree.walk():
        if isinstance(node, _FORBIDDEN_NODES):
            raise SQLValidationError(
                f"SQL contains a forbidden operation: {type(node).__name__}."
            )

    for table in tree.find_all(exp.Table):
        table_name = (table.name or "").lower()
        catalog = (table.catalog or "").lower()
        db = (table.db or "").lower()
        for part in (table_name, catalog, db):
            if part in _FORBIDDEN_TABLES:
                raise SQLValidationError(
                    f"Access to system table/schema '{part}' is not allowed."
                )

    logger.info("SQL validation passed: %.120s…", cleaned)
    return cleaned